name: Go

on: [push]

env:
  GO_VERSION: '>=1.24.0'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04-arm
        - macos-latest
        - windows-latest
    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test ./...

    - name: Build all "main" packages
      shell: bash
      run: |
        go list -f '{{if (eq .Name "main")}}{{.ImportPath}} .{{slice .ImportPath (len .Module.Path)}}{{end}}' ./... | while IFS= read -r line ; do
          read -a e <<< "$line"
          path="${e[0]}"
          dir="${e[1]}"
          name=$(basename $path)
          printf "building %s\t(%s)\n" $name $dir
          ( cd "$dir" && go build )
        done

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
# $Hash:9c8a3b994481420b53acfa5fc528096004ca3db524f1d95554dcbad1$
